insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('asd','asdasd',CURRENT_TIMESTAMP(),null,'asdasdasd',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'asdasd')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Tangó','Jónás legjobb barátja Bali volt a bálna sokat sétálgattak együtt a világ minden táján reggeltől estig estétől reggelik',CURRENT_TIMESTAMP(),null,'Csendesóceán',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kep1')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Rumba','Egy Kettő Három négy',CURRENT_TIMESTAMP(),null,'Rózsa utca 42. ',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kepek/kep2')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Samba','Tánc tánc tánc tánc tánc tánc',CURRENT_TIMESTAMP(),null,'aladár utca 89.',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kep3')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Salsa','Hej az nem is egy tánc',CURRENT_TIMESTAMP(),null,'mert az egy kaja',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kep1')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Keringő','valami valami',CURRENT_TIMESTAMP(),null,'Bécs utca 58.',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kep5')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Swing','jjieikdkkigejikdlsiejkld',CURRENT_TIMESTAMP(),null,'Blaha Lujza tér metró állomás',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kép2')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Sárközi','nos ez felér egy kellemes lábnappal',CURRENT_TIMESTAMP(),null,'gyutacs utca 10.',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kép1')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Szatmári','ez nem csak a lábadat öli meg',CURRENT_TIMESTAMP(),null,'gyutacs utca 10.',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kep3')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Széki lassú','na ebben pihenhetsz',CURRENT_TIMESTAMP(),null,'gyutacs utca 10.',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kep8')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Rúd tánc','kdlsjielklciskeifejso',CURRENT_TIMESTAMP(),null,'valahol ott a feneketlen tó mellett',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kep9')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Limbó','mert miért ne',CURRENT_TIMESTAMP(),null,'kfjklejil',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kep6')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Falu széli Hejderutty nyugatbalatoni dialektusban','igen pont olyan menő mint amilyennek hangzik',CURRENT_TIMESTAMP(),null,'minden esküvőn és utcabálon',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kep4')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Csárdás','egyet jobbra egyet balra',CURRENT_TIMESTAMP(),null,'csuhajja',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kep4')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Zorba','áh úgy sem tudja senki csak fussunk körbe',CURRENT_TIMESTAMP(),null,'kdowik',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'kep3')
insert into course(name,description,create_Date,modify_Date,location,date,dead_Line,max_Number,image) values ('Rózsabimbó','asdasd',CURRENT_TIMESTAMP(),null,'asdasdasd',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),20,'asdasd')

insert into user(email,password,enabled,role,avatar,name) values ('asd.asd.com','$2a$10$c/.qCnqvl7plMmDpIkn.tuT9BaNvEwdifDvK0naj.unS3FNL0d5.a',true,'ROLE_ADMIN','asdgsjfdcbadc','Admin')
insert into user(email,password,enabled,role,avatar,name) values ('tanar.tanar.com','$2a$10$c/.qCnqvl7plMmDpIkn.tuT9BaNvEwdifDvK0naj.unS3FNL0d5.a',true,'ROLE_TEACHER','asdgsjfdcbadc','Tanár')
insert into user(email,password,enabled,role,avatar,name) values ('felh.felh.com','$2a$10$c/.qCnqvl7plMmDpIkn.tuT9BaNvEwdifDvK0naj.unS3FNL0d5.a',true,'ROLE_USER','asdgsjfdcbadc','Táncos1')
insert into user(email,password,enabled,role,avatar,name) values ('tanc.tanc.com','$2a$10$c/.qCnqvl7plMmDpIkn.tuT9BaNvEwdifDvK0naj.unS3FNL0d5.a',true,'ROLE_USER','asdgsjfdcbadc','Táncos2')
insert into user(email,password,enabled,role,avatar,name) values ('tancen.tancen.com','$2a$10$c/.qCnqvl7plMmDpIkn.tuT9BaNvEwdifDvK0naj.unS3FNL0d5.a',true,'ROLE_USER','asdgsjfdcbadc','Táncos3')

insert into applicants_to_course (visited_courses_id,applicants_email) values (1,'asd.asd.com')
insert into applicants_to_course (visited_courses_id,applicants_email) values (1,'felh.felh.com')
insert into applicants_to_course (visited_courses_id,applicants_email) values (1,'tanc.tanc.com')
insert into applicants_to_course (visited_courses_id,applicants_email) values (1,'tancen.tancen.com')
insert into applicants_to_course (visited_courses_id,applicants_email) values (3,'felh.felh.com')
insert into applicants_to_course (visited_courses_id,applicants_email) values (3,'tanc.tanc.com')
insert into applicants_to_course (visited_courses_id,applicants_email) values (3,'tancen.tancen.com')


insert into teachers_to_course (teached_courses_id,teachers_email) values (1,'asd.asd.com')
insert into teachers_to_course (teached_courses_id,teachers_email) values (2,'asd.asd.com')
insert into teachers_to_course (teached_courses_id,teachers_email) values (3,'asd.asd.com')
insert into teachers_to_course (teached_courses_id,teachers_email) values (4,'asd.asd.com')
insert into teachers_to_course (teached_courses_id,teachers_email) values (5,'asd.asd.com')